name: Tiyenti
title: Tiyenti
markdown: kramdown
timezone: Europe/London
defaults:
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: "default"
  -
    scope:
      path: "_posts"
      type: "posts"
    values:
      layout: "post"
      excerpt_separator: <!--more-->