name: Tiyenti
title: Tiyenti's Texts
description: Tiyenti's stuff
author: Tiyenti
markdown: kramdown
timezone: Europe/London
permalink: /blog/:year/:month/:day/:title.html
feed:
  path: /blog/feed.xml
  icon: /favicon.png
defaults:
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: "default"
  -
    scope:
      path: "_posts"
      type: "posts"
    values:
      layout: "post"
      excerpt_separator: "<!--more-->"
plugins:
  - jekyll-feed
